include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  exclude:

linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
