name: fetch_result_bloc
description: A simple package to fetch data from a remote API and return the result as a Bloc state.
version: 1.0.0
repository: https://github.com/nayefradwi/fetch_result_bloc

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  result_flow: ^1.1.1

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0

